# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  ensure_git_status_clean

  desc "Push a new staging build to TestFlight"
  lane :staging do
    changelog = prompt(
      text: "Changelog: ",
      multi_line_end_keyword: "END"
    )
    set_info_plist_value(path: "./FUUTR/Staging-Info.plist", key: "CFBundleVersion", value: (latest_testflight_build_number + 2).to_s)
    increment_build_number_in_plist(target: 'FUUTR-staging')
    build_app(workspace: "FUUTR.xcworkspace", scheme: "FUUTR-staging")
    upload_to_testflight(
      skip_waiting_for_build_processing: false,
      beta_app_description: "fastlane auto build",
      changelog: changelog
    )
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    reset_git_repo(skip_clean: true)
  end
end